#' Populate local-search solutions
#' 
#' @description
#' `blob_populate()` populates solutions generated by the core local-search
#' algorithm implemented in [blob_search()] for a range of cluster numbers (`k`),
#' and relative spatial weights (`r`).
#' 
#' @inheritParams blob_search
#' @param k number of clusters. Either an integer or a vector of length 2.
#' The vector should specify the lower and upper bounds of `k`.
#' @param r spatial relative weight of range \eqn{[0,1]}. Either a numeric value
#' or a vector of length 2. The vector should specify the lower and upper bounds
#' of `r`. Default is `c(0.8,1)`
#' @param run number of runs per `k`. Default is `10L`.
#' @param batch number of batches. Default is `5L`.
#' @param parallel a logical value to parallelise the search. Default is `TRUE`.
#' @param workers number of parallel workers passed onto [future::plan()].
#' Default is `NULL` (`future::availableCores() - 1`).
#' @param progress a logical value to turn on progress bar in the console.
#' Default is `TRUE`.
#' 
#' @details
#' The function is a wrapper of [blob_search()]. By sampling a range of `r`, it
#' populates solutions that approximate the optimal trade-offs between spatial
#' and temporal cost functions (weighted sum scalarisation) for each `k`.
#' Sampling is done by by Latin hypercube sampling ([lhs::randomLHS()]) to
#' generate a near-random sample of parameter values for each batch.
#' Non-dominated solutions are compared across cumulative batches to assess the
#' advance of the Pareto front in [stblob()].
#' 
#' `outlier_removal` is being tested at the moment. The idea is to remove points
#' whose distance to their medoid is considered an outlier based on the
#' interquantile range (IQR) of distances to medoid across \eqn{k} clusters.
#' 
#' 
#' @returns
#' an S3 object of class `pop` with the following components:
#'  * `clust`: a matrix of cluster assignments; row: solution;
#'  column: data point (sample).
#'  * `summary`: a data frame of summary statistics. They include the returning
#'  number of clusters (`k`), original `k` parameter (`k_o`), three
#'  objective values (`space_wcd`, `time_wcr` and `time_wce`), number of
#'  iterations (`iter`), ARI with the previous iteration (`ari`), presence
#'  of intersecting clusters (`intersects`), number of clusters flagged
#'  for expected size (`clustsize_f`), number of outliers (`n_outliers`) and
#'  number of duplicates from other runs (`dup`).
#'  `idx`, `run` and `batch` refer to the index, run and batch of the solution.
#'  * `trace`: a data frame of summary statistics per iteration.
#'  * `filtered_counts`: a data frame of filtered solution counts.
#'  * `data`: a data frame of the input data.
#'  * `params`: a list of parameter values.
#' 
#' @seealso [compute_distmat()], [blob_search()],
#' [sf::st_as_sf()], [sf::st_concave_hull()],
#' [sf::sf_use_s2()], [mclust::adjustedRandIndex()], [future::future],
#' [future.apply::future.apply], [progressr::progressr]
#' 
#' 
#' @export

blob_populate <- function(data,
                          k,
                          r = c(0.8, 1),
                          iter = 10L,
                          run = 10L,
                          batch = 5L,
                          converge_ari = 1,
                          coords = c(1L,2L),
                          age = 3L,
                          crs = 4326,
                          space_distmat = NULL,
                          space_distmethod = NULL,
                          filter_intersects = TRUE,
                          hull_convex_ratio = 0.5,
                          filter_clustsize = TRUE,
                          outlier_removal = TRUE,
                          outlier_iqrm = 1.5,
                          parallel = TRUE,
                          workers = NULL,
                          random_init = FALSE,
                          weights = NULL,
                          sf_use_s2 = TRUE,
                          progress = TRUE) {
  
  # checks
  check_input_bp(data = data,
                 k = k,
                 r = r,
                 iter = iter,
                 run = run,
                 batch = batch,
                 converge_ari = converge_ari,
                 coords = coords,
                 age = age,
                 space_distmat = space_distmat,
                 filter_intersects = filter_intersects,
                 hull_convex_ratio = hull_convex_ratio,
                 filter_clustsize = filter_clustsize,
                 random_init = random_init,
                 weights = weights,
                 sf_use_s2 = sf_use_s2,
                 progress = progress,
                 parallel = parallel,
                 workers = workers)
  
  params <- mget(c("k", "r", "iter", "run", "batch", "converge_ari",
                   "filter_intersects", "hull_convex_ratio", "filter_clustsize",
                   "outlier_removal", "outlier_iqrm", "weights"))
  
  # check if space_distmat is supplied, compute space_distmat otherwise
  space_distmat <- check_space_distmat(data = data,
                                       space_distmat = space_distmat,
                                       space_distmethod = space_distmethod)
  
  data <- as.data.frame(data)
  
  # parameter combinations
  param_cb <- lapply(1:batch, function(i) {
    param_cb <- sample_param_cb(k = k, r = r, run = run)
    param_cb$batch <- i
    return(param_cb)
  })
  param_cb <- do.call(rbind, param_cb)
  
  # param vectors
  param_cb_k <- param_cb$k
  param_cb_r <- param_cb$r
  param_cb_run <- param_cb$run
  param_cb_batch <- param_cb$batch
  
  # parallel computing via future
  if (parallel == TRUE) {
    oplan <- future::plan()                    
    on.exit(future::plan(oplan), add = TRUE)
    workers <- workers %||% (future::availableCores() - 1)
    future::plan(future::multisession, workers = workers)
  }
  
  progressr::with_progress({
    # progress bar along the ncol of param_cb 
    p <- progressr::progressor(along = param_cb_batch) 
    blob_list <- future.apply::future_Map(function(k, r, run, batch) {
      p()
      blob = suppressMessages(
        blob_search(data,
                    k,
                    r,
                    iter = iter,
                    converge_ari = converge_ari,
                    crs = crs,
                    space_distmat = space_distmat,
                    filter_intersects = filter_intersects,
                    hull_convex_ratio = hull_convex_ratio,
                    filter_clustsize = filter_clustsize,
                    outlier_removal = outlier_removal,
                    outlier_iqrm = outlier_iqrm,
                    random_init = random_init,
                    weights = weights,
                    sf_use_s2 = sf_use_s2) 
      )
      
      if (inherits(blob, "blob")) {
        # data is redundant to process here
        blob$data <- NULL
        # label run and batch of the search
        blob$summary$run <- blob$trace$run <- run
        blob$summary$batch <- blob$trace$batch <- batch
        blob <- unclass(blob)
      }
      
      return(blob)
    }, param_cb_k, param_cb_r, param_cb_run, param_cb_batch, future.seed = TRUE)
  }, enable = progress)
  
  pop <- convert_to_pop(blob_list, data = data, params = params)
  return(pop)
}

# print.pop ------------------------------------------------------------------
print.pop <- function(x, ...) {
  cat(paste0("STblob population of ", nrow(x$clust), " solutions\n"),
      "# clusters:\n")
  print(head(x$clust, c(5, 10)))
  if (ncol(x$clust) > 10) cat(paste0(" <", ncol(x$clust) - 10," more columns (points)>\n"))
  if (nrow(x$clust) > 5) cat(paste0(" <", nrow(x$clust) - 5," more rows (solutions)>\n"))
  cat("\n")
  cat("# summary:\n")
  print(head(x$summary, 5))
  if (nrow(x$summary) > 5) cat(paste0(" <", nrow(x$summary) - 5," more rows>\n"))
  cat("\n")
  cat("# trace:\n")
  print(head(x$trace, 5))
  if (nrow(x$trace) > 5) cat(paste0(" <", nrow(x$trace) - 5," more rows>\n"))
  cat("\n")
  cat("# filtered solution counts:\n")
  print(x$filtered_counts)
  invisible(x)
}

# summary.pop ----------------------------------------------------------------
summary.pop <- function(x, ...) {
  print(x$summary)
  invisible(x)
}

# helpers ---------------------------------------------------------------------
## check_input_bp -------------------------------------------------------------
check_input_bp <- function(data,
                           k,
                           r,
                           iter,
                           run,
                           batch,
                           converge_ari,
                           coords,
                           age,
                           space_distmat,
                           filter_intersects,
                           hull_convex_ratio,
                           filter_clustsize,
                           random_init,
                           weights,
                           sf_use_s2,
                           progress,
                           parallel,
                           workers) {
  stopifnot(
    "`data` must be a data frame or matrix" = is.data.frame(data) || is.matrix(data),
    "`data` must have at least 3 columns" = ncol(data) >= 3L,
    "`k` must be greater than 1" =
      all(k > 1L) && (length(r) == 1L || length(r) == 2L),
    "`r` must be between 0 and 1" =
      all(r >= 0) && all(r <= 1) && (length(r) == 1L || length(r) == 2L),
    "`iter` must be at least 3" = iter >= 3L,
    "`run` must be at least 1" = run >= 1L,
    "`batch` must be at least 1" = batch >= 1L,
    "`converge_ari` must be between 0 and 1" = converge_ari >= 0 && converge_ari <= 1,
    "`filter_intersects` must be logical" = is.logical(filter_intersects),
    "`hull_convex_ratio` must be between 0 and 1" = hull_convex_ratio >= 0 && hull_convex_ratio <= 1,
    "`filter_clustsize` must be logical" = is.logical(filter_clustsize),
    "`random_init` must be logical" = is.logical(random_init),
    "`sf_use_s2` must be logical" = is.logical(sf_use_s2),
    "`progress` must be logical" = is.logical(progress),
    "`parallel` must be logical" = is.logical(parallel)
  )
  
  check_col_ref(coords, data, "coords", expected_length = 2L)
  check_col_ref(age, data, "age", expected_length = 1L)
  
  n <- if (!is.null(space_distmat)) nrow(space_distmat) else nrow(data)
  
  if (!is.null(space_distmat)) {
    stopifnot("`space_distmat` must be a numeric matrix or a `dist` object" =
                is.numeric(space_distmat),
              "`space_distmat` must have the same number of rows as `data`" =
                nrow(data) == nrow(space_distmat))
  }
  
  if (!is.null(weights)) {
    stopifnot("`weights` must be numeric" =
                is.numeric(weights),
              "`weights` must have length equal to number of rows in `data`" =
                length(weights) == n)
  }
  
  if(!is.null(workers)) {
    stopifnot("`workers` must be at least 2" = workers > 1L)
  }
  
  invisible(NULL)
}

## sample_r -------------------------------------------------------------------
sample_r <- function(r, run) {
  if (length(r) == 2) {
    # LHS sampling for more evenly distributed parameters
    lhs_samples <- lhs::randomLHS(run,1)
    # scale to the range
    r_samples <- sort(as.vector(min(r) + lhs_samples * (max(r) - min(r))))
  } else {
    r_samples <- rep(r,run)
  }
  return(r_samples)
}
## sample_param_cb ------------------------------------------------------------
sample_param_cb <- function(k, r, run) {
  K <- if (length(k) == 2L) k[1]:k[2] else k
  R <- sample_r(r, run)
  RUN <- 1:run
  # parameter combination
  param_cb <- expand.grid(k = K, r = R)
  # index the run
  R_run_cb <- data.frame(r = R, run = RUN)
  param_cb <- merge(param_cb, R_run_cb, all.x = TRUE)
  return(param_cb)
}

## convert_to_pop -------------------------------------------------------------
convert_to_pop <- function(blob_list, data, params = NULL) {
  # summarise invalid runs
  invalid_runs <- which(sapply(blob_list, function(x) is.numeric(x)))
  invalid_counts <- summarise_invalid(blob_list, invalid_runs)
  
  # combine output from valid runs
  total_runs <- 1:length(blob_list)
  valid_runs <- total_runs[-invalid_runs]
  valid_len <- length(valid_runs)
  
  # rbind the list of output from different runs 
  if (valid_len > 0) {
    blob_list <- blob_list[valid_runs]
    pop <- list()
    for (l in c("clust", "summary", "trace")) {
      # extract the df
      e <- lapply(blob_list, function(x) x[[l]])
      if (l %in% c("summary", "trace")) {
        e <- Map(function(x,y) {
          x$idx <- y
          x <- x[c("idx", setdiff(names(x), "idx"))]
          return(x)
          }, e, 1:length(e))
      }
      e <- do.call(rbind, e)
      pop[[l]] <- e
    }
    
    clust <- pop$clust
    summary <- pop$summary
    trace <- pop$trace
    
    # find, label and remove the duplicates
    if (valid_len > 1) {
      dup <- find_dup(clust)
      # duplicated indices
      dup_idx <- dup$idx
      
      if (length(dup_idx) > 0) {
        # record the freq
        summary$dup <- 0
        summary$dup[dup$freq$idx] <- dup$freq$n
        invalid_counts$n[5] <- sum(dup$freq$n)
        # remove the runs from the output
        clust <- clust[-dup_idx, ]
        summary <- subset(summary, !idx %in% dup_idx)
        trace <- subset(trace, !idx %in% dup_idx)
        # reindex the output
        rownames(summary) <- NULL
        summary$idx <- match(summary$idx, unique(summary$idx))
        rownames(trace) <- NULL
        trace$idx <- match(trace$idx, unique(trace$idx))
      }
    }
  } else {
    clust <- summary <- trace <- NULL
  }
  
  # more understandable
  filtered_counts <- invalid_counts
  
  if (is.null(clust)) message("No feasible solution is found.")
  
  return(new_pop(clust = clust,
                 summary = summary,
                 trace = trace,
                 filtered_counts = filtered_counts,
                 data = data,
                 params = params))
}

## summarise_invalid ----------------------------------------------------------
summarise_invalid <- function(blob_list, invalid_run = NULL) {
  # blob_list: a list of blob objects or alike
  # invalid_run: skip looking for status output from the list if supplied
  # dup is not really invalid but included here to make the code cleaner
  invalid_run <- invalid_run %||% which(sapply(blob_list, function(x) is.numeric(x)))
  status <- unlist(blob_list[invalid_run])
  status_counts <- as.data.frame(table(status), responseName = "n")
  status_counts <- merge(data.frame(status = c(1,2,3,4,5)), status_counts,
                         all.x = TRUE)
  status_counts[is.na(status_counts)] <- 0
  
  status_counts$status <- sapply(status_counts$status,
                                 function(x) switch(x,
                                                    "1" = "k1",
                                                    "2" = "intersects",
                                                    "3" = "clustsize",
                                                    "4" = "intersects_clustsize",
                                                    "5" = "dup"))
  return(status_counts)
}

## new_pop --------------------------------------------------------------------
new_pop <- function(clust, summary, trace, filtered_counts, data, params) {
  stopifnot(is.null(clust) || is.matrix(clust),
            is.null(summary) || is.data.frame(summary),
            is.null(trace) || is.data.frame(trace),
            is.data.frame(filtered_counts),
            is.data.frame(data),
            is.null(params) || is.list(params))
  
  structure(
    list(clust = clust,
         summary = summary,
         trace = trace,
         filtered_counts = filtered_counts,
         data = data,
         params = params),
    class = "pop"
  )
}