#' Populate local-search solutions
#' 
#' @description
#' `blob_populate()` populates solutions generated by the core local-search
#' algorithm ([blob_search()]) for a range of cluster numbers (`k`),
#' and relative spatial weights (`w_space`).
#' 
#' @inheritParams stblob_lsearch
#' @param k number of clusters. Either an integer or integer sequence.
#' @param w_space relative spatial weight of range \eqn{[0,1]}.
#' Either a numeric value or a vector of length 2.
#' The vector should specify the lower and upper bounds.
#' @param optim_type_diversity a logical value to optimise data type diversity.
#' Default is `FALSE`.
#' @param w_time relative spatial weight of range \eqn{[0,1]}. Default is `NULL`,
#' Supply a numeric value when fixed weights across runs are used.
#' @param w_time relative spatial weight of range \eqn{[0,1]}. Default is `NULL`,
#' Supply a numeric value when fixed weights across runs are used.
#' @param run number of runs per \eqn{k}. Default is `10L`.
#' @param batch number of batches. Default is `NULL`.
#' @param parallel a logical value to parallelise the search. Default is `TRUE`.
#' @param workers number of parallel workers passed onto [future::plan()].
#' Default is `NULL` with `future::availableCores() - 1`.
#' @param ... other additional arguments. 
#' @inheritDotParams stblob_lsearch
#' 
#' @details
#' The function is a wrapper of [stblob_lsearch()].
#' By sampling a range of parameter combinations of `w_space`, `w_time` and `w_type`,
#' it populates solutions that locally optimise trade-offs between spatial,
#' temporal and data type diversity cost functions using augmented weighted
#' Chebyshev (Tchebycheff) scalarisation (Steuer & Choo, 1983)
#' across \eqn{k} clusters.
#' Sampling is done via Latin hypercube sampling ([lhs::randomLHS()]) for a
#' single free parameter, otherwise via sampling from a Dirichlet distribution
#' with \eqn{\alpha = \(1,1,1)\)} ([MCMCack::rdirichlet()]).
#' ###
#' Non-dominated solutions are then compared across cumulative batches to assess
#' the advance of the Pareto front in [stblob()].
#' ###
#' 
#' `outlier_removal` is being tested at the moment. The idea is to remove points
#' whose distance to their medoid is an outlier based on the
#' interquantile range (IQR) of distances to medoid across \eqn{k} clusters.
#' 
#' @returns
#' an S3 object of class `pop` with the following components:
#'  * `clust`: a matrix of cluster assignments; row: solution;
#'  column: data point.
#'  * `summary`: a data frame of summary statistics. They include the parameter
#'  value of (`k`), number of clusters of the output (`k_o`), three
#'  objective values (`z_space`, `z_time1`, `z_time2` and `z_type`),
#'  number of iterations (`iter`), ARI with the previous iteration (`ari`),
#'  state of local search convergence (`ls_convergence`)
#'  and number of outliers (`n_outliers`).
#'  * `trace`: a data frame of summary statistics for each iteration.
#'  * `data`: a data frame of the input data.
#'  * `filter_summary`: a data frame of filter summary.
#'  * `params`: a list of parameter values.
#' 
#' @seealso [compute_distmat()], [stblob_search()],
#' [sf::st_as_sf()], [sf::st_concave_hull()],
#' [sf::sf_use_s2()], [aricode::ARI()], [future::future],
#' [future.apply::future.apply], [progressr::progressr]
#' 
#' @references
#' Steuer, R. E., & Choo, E.-U. (1983). An interactive weighted Tchebycheff
#' procedure for multiple objective programming. Mathematical Programming,
#' 26(3), 326–344.
#' 
#' @export

stblob_populate <- function(data,
                            k,
                            w_space,
                            optim_type_diversity = FALSE,
                            iter = 10L,
                            run = 10L,
                            batch = 10L,
                            w_time = NULL,
                            w_type = NULL,
                            
                            # additional input arguments like column names
                            coords = NULL,
                            age = NULL,
                            type = NULL,
                            space_distmat = NULL,
                            space_distmethod = c("geodesic", "euclidean"),
                            
                            # future.apply
                            parallel = TRUE,
                            workers = NULL,
                            
                            # constraints and additional local-search arguments
                            ...
                            # ls_tol = 0,
                            # filter_intersects = TRUE,
                            # hull_convex_ratio = 0.5,
                            # hull_crs = 4326,
                            # filter_clustsize = TRUE,
                            # outlier_removal = FALSE,
                            # outlier_iqrm = 1.5,
                            # chebyshev_rho = 1e-4,
                            # random_init = FALSE,
                            # sf_use_s2 = TRUE
                            ) {
  
  params <- c(mget(ls(environment(), sorted = FALSE)),
              match.call(expand.dots = FALSE)$...)
  params$data <- params$space_distmat <- NULL
  
  # check data
  stopifnot("'data' must be a data.frame" = is.data.frame(data))
  
  # check columns
  coords <- if (!is.null(coords)) match(coords, names(data)) else names(data)[c(2,3)]
  age <- if (!is.null(age)) match(age, names(data)) else names(data)[4]
  type <- if (!is.null(type)) match(type, names(data)) else names(data)[5]
  
  # type may not be a column of optim_type_diversity is turned off
  if (!optim_type_diversity) type <- NULL
  
  stopifnot(
    "'coords' do not match any column names" = !any(is.na(coords)),
    "'age' does not match any column names" = !any(is.na(age)),
    "'type' does not match any column names" = !any(is.na(type)),
    "'coords' must be numeric" = is.numeric(data[[coords[1]]]) & is.numeric(data[[coords[2]]]),
    "'age' must be numeric" = is.numeric(data[[age]])
  )
  
  # check if space_distmat is supplied, compute space_distmat otherwise
  space_distmat <- check_space_distmat(data = data,
                                       coords = coords,
                                       space_distmat = space_distmat,
                                       space_distmethod = space_distmethod)
  
  # in case crs is not specified otherwise
  if (space_distmethod == "euclidean") hull_crs <- NA
  
  # check_opt_args
  check_opt_args(...)
  
  # check populate related args
  stopifnot(
    "'run' must be at least 2" = run > 1L,
    "'batch' must be at least 1" =  batch > 0L,
    "'parallel' must be logical" = is.logical(parallel)
  )
  
  # parallel computing via future
  if (parallel) {
    oplan <- future::plan()                    
    on.exit(future::plan(oplan), add = TRUE)
    workers <- workers %||% (future::availableCores() - 1)
    future::plan(future::multisession, workers = workers)
  }
  
  # parameter combinations
  param_grid_list <- lapply(1:batch, function(i) {
    param_grid <- sample_param_grid(k = k,
                                    w_space = w_space,
                                    run = run,
                                    optim_type_diversity = optim_type_diversity,
                                    w_time = w_time,
                                    w_type = w_type)
    param_grid$batch <- i
    return(param_grid)
  })
  
  param_grid <- do.call(rbind, param_grid_list)

  # number of searches to perform
  NS <- nrow(param_grid)
  
  # param vectors
  grid_k <- param_grid$k
  grid_w_space <- param_grid$w_space
  grid_w_time <- param_grid$w_time
  grid_w_type <- param_grid$w_type
  grid_run <- param_grid$run
  grid_batch <- param_grid$batch
  
  # progress bar along the ncol of param_grid
  p <- progressr::progressor(along = 1:NS)

  sol_list <- future.apply::future_Map(function(k, w_space, w_time, w_type, run, batch) {
    # switch NA back to NULL
    w_type <- if (is.na(w_type)) NULL
    
    sol <- suppressMessages(
      stblob_lsearch(data = data,
                     k = k,
                     w_space = w_space, 
                     optim_type_diversity = optim_type_diversity,
                     w_time = w_time,
                     w_type = w_type,
                     iter = iter,
                     coords = coords, 
                     age = age, 
                     type = type, 
                     space_distmat = space_distmat,
                     space_distmethod = space_distmethod, 
                     ...)
    )
    
    # data and space_distmat are redundant to process here
    sol$data <- NULL
    sol$space_distmat <- NULL
    
    if (sol$status == 0) {
      # label run and batch of the search
      sol$summary$run <- sol$trace$run <- run
      sol$summary$batch <- sol$trace$batch <- batch
    }
    
    sol <- unclass(sol)
    
    # progress
    p() 
    
    return(sol)
  },
  grid_k, grid_w_space, grid_w_time, grid_w_type, grid_run, grid_batch,
  future.seed = TRUE)
  
  pop <- convert_to_pop(sol_list, data = data, space_distmat, params = params)
  
  return(pop)
}

# print.pop ------------------------------------------------------------------
print.stblob_pop <- function(x, ...) {
  if (!is.null(x$clust)) {
    cat("STblob population of", nrow(x$clust), "solutions\n")

    cat("$clust\n# cluster assignments:\n")
    print(head(x$clust, c(5, 10)))
    if (ncol(x$clust) > 10) cat(paste0(" <", ncol(x$clust) - 10," more columns (points)>\n"))
    if (nrow(x$clust) > 5) cat(paste0(" <", nrow(x$clust) - 5," more rows (solutions)>\n"))
    cat("\n")
    
    cat("$summary\n# summary:\n")
    print(head(x$summary, 5))
    if (nrow(x$summary) > 5) cat(paste0(" <", nrow(x$summary) - 5," more rows>\n"))
    cat("\n")
    
    cat("$filter_summary\n# number of passed and filtered solutions: \n")
    print(x$filter_summary[c("k",
                             "pass",
                             "k1",
                             "intersects",
                             "clustsize",
                             "intersects_clustsize",
                             "dup")])
    cat("\n")
    cat("# upper quartiles of 'w_space' of solutions with intersects: \n")
    print(x$filter_summary[c("k",
                             "w_space_q3")])
    cat("\n")
    
    
  } else {
    cat("No feasible solution was found.\n")
    cat("\n")
    
    cat("# number of filtered solutions:\n")
    print(x$status_counts)
  }
  
  invisible(x)
}

# summary.pop ----------------------------------------------------------------
summary.stblob_pop <- function(x, ...) {
  print(x$summary)
  invisible(x)
}

# helpers ---------------------------------------------------------------------
## sample_param_grid ----------------------------------------------------------
sample_param_grid <- function(k,
                              w_space,
                              run,
                              optim_type_diversity,
                              w_time = NULL,
                              w_type = NULL) {
  # checks
  if (is.list(w_space)) {
    if (length(w_space) != 1) {
      stopifnot("'w_space' must be a list length equal to length of 'k'" =
                  length(w_space) == length(k))
    }
  } else {
    w_space <- list(w_space)
  }
  
  if (is.list(w_time)) {
    if (length(w_time) != 1) {
      stopifnot("'w_time' must be a list length equal to length of 'k'" =
                  length(w_time) == length(k))
    }
  } else {
    w_time <- list(w_time)
  }
  
  if (is.list(w_type)) {
    if (length(w_type) != 1) {
      stopifnot("'w_time' must be a list length equal to length of 'k'" =
                  length(w_type) == length(k))
    }
  } else {
    w_type <- list(w_type)
  }
  
  # Map() cannot deal with NULL, NULL -> NA
  w_time <- lapply(w_time, function(x) x <- x %||% NA)
  w_type <- lapply(w_type, function(x) x <- x %||% NA)
  
  w_grid <- Map(function(x, y, z) {
    # switch NA back to NULL for sample_w()
    y <- if (is.na(y)) NULL
    z <- if (is.na(z)) NULL
    sample_w(w_space = x,
             run = run,
             optim_type_diversity = optim_type_diversity,
             w_time = y,
             w_type = z)},
    w_space, w_time, w_type)
  
  if (length(w_grid) != length(k)) w_grid <- rep(w_grid, length(k))
  
  param_grid <- Map(function(x, y) cbind(k = x, y), k, w_grid)
  param_grid <- do.call(rbind, param_grid)
  
  return(param_grid)
}

## sample_w -------------------------------------------------------------------
sample_w <- function(w_space,
                     run,
                     optim_type_diversity,
                     w_time = NULL,
                     w_type = NULL) {
  
  w <- NULL
  w_lens <- vapply(list(w_space, w_time, w_type), length, numeric(1L))
  
  stopifnot("'w_space', 'w_time' and 'w_type' must be between 0 and 1" =
            all(unlist(c(w_space, w_time, w_type)) >= 0) & all(unlist(c(w_space, w_time, w_type)) <= 1))
  
  if (!optim_type_diversity) {
    
    if (w_lens[1] == 2) {
      # Latin hypercube sampling
      lhs_samps <- lhs::randomLHS(run, 1)
      w1 <- sort(as.vector(min(w_space) + lhs_samps * (max(w_space) - min(w_space))))
      w2 <- 1 - w1
    } else {
      w1 <- rep(w_space, run)
      w2 <- 1 - w1
    }
    
    w <- data.frame(w_space = w1, w_time = w2, w_type = NA)
    
  } else {
    
    if (w_lens[1] == 1) {
      
      w1 <- rep(w_space, run)
      
      if (all(w_lens == 1)) {
        
        stopifnot("'w_space', 'w_time' and 'w_type' must sum up to 1" =
                    all.equal(sum(w_space, w_time, w_type), 1))
        
        w2 <- rep(w_time, run)
        w3 <- rep(w_type, run)
        
      } 
      
      if (sum(w_lens == 1) == 2) {
        
        stopifnot("'w_space', 'w_time' and 'w_type' must sum up to 1" =
                    sum(w_space, w_time, w_type) <= 1)
        
        if (w_lens[2] == 1) {
          w2 <- rep(w_time, run)
          w3 <- 1 - w1 - w2
        }
        
        if (w_lens[3] == 1) {
          w3 <- rep(w_type, run)
          w2 <- 1 - w1 - w3
        }
        
      }
      
      if (sum(w_lens == 1) == 1) {
        
        if (w_space == 1) {
          w2 <- 1 - w1
          w3 <- 1 - w1
        }
        
        if (w_space < 1) {
          w_time <- c(1 - w_space, 0)
          # Latin hypercube sampling
          lhs_samps <- lhs::randomLHS(run, 1)
          w2 <- sort(as.vector(min(w_time) + lhs_samps * (max(w_time) - min(w_time))))
          w3 <- 1 - w1 - w2
        }
        
      }
      
      w <- data.frame(w_space = w1, w_time = w2, w_type = w3)
      if (any(abs(w) < .Machine$double.eps ^ 0.5)) w[abs(w) < .Machine$double.eps ^ 0.5] <- 0
    }
    
    if (w_lens[1] == 2) {
      w <- data.frame()
      while (nrow(w) < run) {
        dirchlet_samp <- MCMCpack::rdirichlet(1, c(1,1,1))
        # reject sample if w_space is outside the constraint
        if (dirchlet_samp[1] >= min(w_space) &
            dirchlet_samp[1] <= max(w_space)) {
          w <- rbind(w, dirchlet_samp)}
      }
      names(w) <- c("w_space", "w_time", "w_type")
    }
  }
  
  # index the run
  w$run <- 1:nrow(w)
  return(w)
}

## convert_to_pop -------------------------------------------------------------
convert_to_pop <- function(sol_list, data, space_distmat, params) {
  # summarise invalid runs
  invalid_idx <- which(vapply(sol_list, function(x) x$status > 0, logical(1L)))
  filter_summary <- summarise_filter(sol_list = sol_list, invalid_idx = invalid_idx)

  
  # combine output from valid runs
  runs <- 1:length(sol_list)
  runs_pass <- runs[!runs %in% invalid_idx]
  # runs_valid <- if (length(invalid_idx) > 0) runs[-invalid_idx] else runs
  len_pass <- length(runs_pass)
  
  # rbind the list of output from different runs 
  if (len_pass > 0) {
    s <- sol_list[runs_pass]
    pop <- list()
    for (l in c("clust", "summary", "trace")) {
      # extract the df
      e <- lapply(s, function(x) x[[l]])
      if (l %in% c("summary", "trace")) {
        e <- Map(function(x,y) {
          x$idx <- y
          x <- x[c("idx", setdiff(names(x), "idx"))]
          return(x)
          }, e, 1:length(e))
      }
      e <- do.call(rbind, e)
      pop[[l]] <- e
    }
    
    clust <- pop$clust
    summary <- pop$summary
    trace <- pop$trace
    
    # find, label and remove the duplicates
    if (len_pass > 1) {
      dup <- duplicated(clust)
      # duplicated indices
      dup_idx <- which(dup)
      
      if (length(dup_idx) > 0) {
        # parameter k to split dup count
        dup_idx_k <- split(dup_idx, summary$k[dup_idx])
        
        # record the freq
        dup_counts <- vapply(dup_idx_k, function(x) length(x), numeric(1L))
        dup_counts <- as.data.frame(dup_counts)
        dup_counts <- cbind(as.numeric(rownames(dup_counts)), dup_counts)
        names(dup_counts) <- c("k", "dup")
        
        # update filter_summary
        filter_summary <- merge(filter_summary, dup_counts, all.x = TRUE)
        filter_summary$dup[is.na(filter_summary$dup)] <- 0
        filter_summary$pass <- filter_summary$pass - filter_summary$dup
        
        # remove the runs from the output
        clust <- unique(clust)
        summary <- subset(summary, !idx %in% dup_idx)
        trace <- subset(trace, !idx %in% dup_idx)
        # reindex the output
        rownames(summary) <- NULL
        summary$idx <- match(summary$idx, unique(summary$idx))
        rownames(trace) <- NULL
        trace$idx <- match(trace$idx, unique(trace$idx))
      } else {
        # no duplicates
        filter_summary$dup <- 0
      }
    }
  } else {
    clust <- summary <- trace <- NA
    filter_summary$dup <- 0
  }
  
  # reorder columns
  filter_summary <- filter_summary[c("k",
                                     "pass",
                                     "k1",
                                     "intersects",
                                     "clustsize",
                                     "intersects_clustsize",
                                     "dup",
                                     "w_space_q3")]
  
  if (all(is.na(clust))) message("No feasible solution was found.")
  
  return(new_pop(clust = clust,
                 summary = summary,
                 trace = trace,
                 data = data,
                 space_distmat = space_distmat,
                 filter_summary = filter_summary,
                 params = params))
}

## summarise_filter -----------------------------------------------------------
summarise_filter <- function(sol_list, invalid_idx = NULL) {
  # sol_list: a list of sol objects or alike
  # invalid_idx: skip looking for status output from the list if supplied
  invalid_idx <- invalid_idx %||% which(vapply(sol_list, function(x) x$status > 0, logical(1L)))
  
  # k params for each sol
  k <- vapply(sol_list, function(x) x$params$k, numeric(1L))
  K <- sort(unique(k))
  
  status <- vapply(sol_list, function(x) x$status, numeric(1L))
  w_space <- vapply(sol_list, function(x) x$params$w_space, numeric(1L))
  # subset status intersect
  w_space[!(status == 2 | status == 4)] <- NA
    
  if (length(status) > 0) {
    # status
    status_counts <- lapply(split(status, k), function(x) {
      s <- numeric(5L)
      x <- table(x)
      s[(as.numeric(names(x))+1)] <- x
      return(s)
      })
    
    status_counts <- as.data.frame(do.call(rbind, status_counts))
    # get column from rownames
    status_counts <- cbind(as.numeric(rownames(status_counts)), status_counts)
    # name the columns
    colnames(status_counts) <- c("k", "pass", "k1", "intersects",
                                 "clustsize", "intersects_clustsize")
    # obtain all k for the df
    status_counts <- merge(data.frame(k = K), status_counts, all.x = TRUE)
    status_counts[is.na(status_counts)] <- 0
    
    # Q3 of w_space parameter values of solutions with intersects
    ws_q3 <- lapply(
      split(w_space, k),
      function(x) as.numeric(stats::quantile(x, probs = 0.75, na.rm = TRUE))
    )
    ws_q3 <- as.data.frame(do.call(rbind, ws_q3))
    # get column from rownames
    ws_q3 <- cbind(as.numeric(rownames(ws_q3)), ws_q3)
    # name the columns
    colnames(ws_q3) <- c("k", "w_space_q3")
    # obtain all k for the df
    ws_q3 <- merge(data.frame(k = K), ws_q3, all.x = TRUE)
    
    # combine into filter_summary
    filter_summary <- merge(status_counts, ws_q3)
    
  } else {
    filter_summary <- data.frame(k = K,
                                 k1 = 0,
                                 intersects = 0,
                                 clustsize = 0,
                                 intersects_clustsize = 0,
                                 w_space_q3 = NA)
  }
  
  return(filter_summary)
}

## new_pop --------------------------------------------------------------------
new_pop <- function(clust, summary, trace, data, space_distmat, filter_summary, params) {
  stopifnot(is.matrix(clust) || (length(clust) == 1 && all(is.na(clust))) ,
            is.data.frame(summary) || (length(summary) == 1 && all(is.na(summary))),
            is.data.frame(trace) || (length(trace) == 1 && all(is.na(trace))),
            is.data.frame(data),
            is.matrix(space_distmat),
            is.data.frame(filter_summary),
            is.null(params) || is.list(params))
  
  structure(
    list(clust = clust,
         summary = summary,
         trace = trace,
         data = data,
         space_distmat = space_distmat,
         filter_summary = filter_summary,
         params = params),
    class = "stblob_pop"
  )
}
