#' STblob algorithm
#' 
#' @description
#' `stblob()` populates solutions generated by the core local-search
#' algorithm implemented in [blob_search()] for a range of cluster numbers (`k`),
#' and relative spatial weights (`r`) and performs multi-objective optimisation
#' (MOO) to approximate the Pareto front of spatiotemporal partitions.
#' 
#' @inheritParams blob_search
#' @inheritParams blob_populate
#' @param pareto_ari a numeric value of the Adjusted Rand Index (ARI)
#' that sets the similarity threshold between two Pareto optimal solutions.
#' Default is `1`.
#' 
#' @details
#' STblob (SpatioTemporal Blob Optimisation Algorithm) performs multi-objective
#' optimisation (MOO) by implementing a local-search algorithm
#' (see [blob_search()]) in a MOO framework.
#' By sampling a range of `r`, it populates solutions that approximate the
#' optimal trade-offs between spatial and temporal cost functions (weighted sum
#' scalarisation) for each `k`. Sampling is done by by Latin hypercube sampling
#' ([lhs::randomLHS()]) to generate a near-random sample of parameter values for
#' each batch. To approximate the global optimal trade-offs, non-dominated
#' solutions are compared across cumulative batches to assess the advance of the
#' Pareto front based on three objectives:
#' 
#' * `space_wcd` Within-cluster spatial sum of distances to their corresponding
#' cluster medoids (total sum)
#' * `time_wcr` Within-cluster temporal range (average across clusters)
#' * `time_wce` Within-cluster temporal evenness (average across clusters)
#' 
#' Three commonly used quality indicators used to evaluate the advance of Pareto
#' front in a normalised objective space with resepct to all batches, namely
#' the inverted generational distance (IGD) (Coello Coello & Reyes Sierra, 2004),
#' IGD+ (Ishibuchi et al., 2015) and hypervolume (Zitzler & Thiele, 1998) (see
#' also [moocore::igd()], [moocore::igd_plus()] and [moocore::hypervolume()]).
#' For IGD and IGD+, a reference set of points is needed. In our case, the Pareto
#' front of the later batch is used as the reference to that of the previous.
#' For hypervolume, a vector of \eqn{(1.1, 1.1, 1.1)} is used as the reference
#' point.
#' 
#' `outlier_removal` is being tested at the moment. The idea is to remove points
#' whose distance to their medoid is considered an outlier based on the
#' interquantile range (IQR) of distances to medoid across \eqn{k} clusters.
#' 
#' This function is a wrapper of [blob_populate()], [eval_moo()] and [filter_pareto()].
#' 
#' @returns
#' an S3 object of class `stblob` with the following components:
#'  * `pareto_idx`: indices of selected solutions on the Pareto front, ordered by
#'  increasing `space_wcd`, decreasing `time_wcr` and `time_wce`. The index
#'  corresponds to the row of `clust`.
#'  * `clust`: a matrix of cluster assignments; row: solution;
#'  column: data point (sample).
#'  * `summary`: a data frame of summary statistics. They include the returning
#'  number of clusters (`k`), original `k` parameter (`k_o`), three
#'  objective values (`space_wcd`, `time_wcr` and `time_wce`), number of
#'  iterations (`iter`), ARI with the previous iteration (`ari`), presence
#'  of intersecting clusters (`intersects`), number of clusters flagged
#'  for expected size (`clustsize_f`), number of outliers (`n_outliers`) and
#'  number of duplicates from other runs (`dup`). 
#'  `idx`, `run` and `batch` refer to the index, run and batch of the solution.
#'  `sel` and `pareto` indicate the selected solutions and all solutions in the
#'  Pareto front respectively.
#'  * `trace`: a data frame of summary statistics per iteration.
#'  * `filtered_counts`: a data frame of filtered solution counts.
#'  * `moo_eval`: a data frame of MOO optimisation performance summary with quality
#'  indicatores measuring the advance of empirical Pareto (non-dominated) front.
#'  * `obj`: objectives.
#'  * `data`: a data frame of the input data.
#'  *`pareto_idx_l`: a list of non-dominated solutions from every cumulative batch.
#'  * `params`: a list of parameter values.
#' 
#' @seealso [compute_distmat()], [blob_search()], [blob_populate()],
#' [eval_moo()], [filter_pareto()],
#' [moocore::is_nondominated()], [moocore::igd()],
#' [moocore::igd_plus()], [moocore::igd_hypervolume()],
#' [sf::st_as_sf()], [sf::st_concave_hull()],
#' [sf::sf_use_s2()], [mclust::adjustedRandIndex()], [future::future],
#' [future.apply::future.apply], [progressr::progressr]
#' 
#' @references
#' Carlos A Coello Coello and Margarita Reyes Sierra. “A study of the parallelization of a
#' co-evolutionary multi-objective evolutionary algorithm”. In: MICAI 2004: Advances in Artificial
#' Intelligence. Lecture notes in computer science. Berlin, Heidelberg: Springer Berlin Heidelberg,
#' 2004, pp. 688–697.
#' 
#' Hisao Ishibuchi et al. “Modified distance calculation in generational distance and inverted
#' generational distance”. en. In: Lecture Notes in Computer Science. Lecture notes in computer
#' science. Cham: Springer International Publishing, 2015, pp. 110–125
#' 
#' Eckart Zitzler and Lothar Thiele. “Multiobjective optimization using evolutionary algorithms
#' — A comparative case study”. en. In: Lecture Notes in Computer Science. Lecture notes in
#' computer science. Berlin, Heidelberg: Springer Berlin Heidelberg, 1998, pp. 292–301.
#' 
#' Kaisa Miettinen. Nonlinear Multiobjective Optimization. en. 1998th ed. International Series in
#' Operations Research & Management Science. Dordrecht, Netherlands: Springer, Sept. 1998.
#' 
#' 
#' 
#' @export

stblob <- function(data,
                   k,
                   r = c(0.8, 1),
                   iter = 10L,
                   run = 10L,
                   batch = 5L,
                   converge_ari = 1,
                   coords = c(1,2),
                   age = 3,
                   crs = 4326,
                   space_distmat = NULL,
                   space_distmethod = NULL,
                   filter_intersects = TRUE,
                   hull_convex_ratio = 0.5,
                   filter_clustsize = TRUE,
                   outlier_removal = FALSE,
                   outlier_iqrm = 1.5,
                   pareto_ari = 0.8,
                   parallel = TRUE,
                   workers = NULL,
                   random_init = FALSE,
                   weights = NULL,
                   sf_use_s2 = TRUE,
                   progress = TRUE) {
  # checks
  check_input_bp(data = data,
                 k = k,
                 r = r,
                 iter = iter,
                 run = run,
                 batch = batch,
                 converge_ari = converge_ari,
                 coords = coords,
                 age = age,
                 space_distmat = space_distmat,
                 filter_intersects = filter_intersects,
                 hull_convex_ratio = hull_convex_ratio,
                 filter_clustsize = filter_clustsize,
                 random_init = random_init,
                 weights = weights,
                 sf_use_s2 = sf_use_s2,
                 progress = progress,
                 parallel = parallel,
                 workers = workers)
  
  stopifnot("`pareto_ari` must be between 0 and 1" =  pareto_ari >= 0 && pareto_ari <= 1,
            "`batch` must be at least 2" =  batch > 1L)

  # blob_populate()
  pop <- blob_populate(data = data,
                       k = k,
                       r = r,
                       iter = iter,
                       run = run,
                       batch = batch,
                       converge_ari = converge_ari,
                       coords = coords,
                       age = age,
                       crs = crs,
                       space_distmat = space_distmat,
                       space_distmethod = space_distmethod,
                       filter_intersects = filter_intersects,
                       hull_convex_ratio = hull_convex_ratio,
                       filter_clustsize = filter_clustsize,
                       outlier_removal = outlier_removal,
                       outlier_iqrm = outlier_iqrm,
                       parallel = parallel,
                       workers = workers,
                       random_init = random_init,
                       weights = weights,
                       sf_use_s2 = sf_use_s2,
                       progress = progress)
  
  # eval_moo()
  stblob <- eval_moo(pop = pop, pareto_ari = pareto_ari)
  
  return(stblob)
}

# eval_moo -------------------------------------------------------------------
#' Evaluate multi-objective optimisation (MOO) performance
#' 
#' @description
#' `eval_moo()` evaluates MOO performance on batches of solutions.
#' 
#' @inheritParams stblob
#' @param pop an S3 `pop` object.
#' 
#' @inheritSection stblob returns
#' 
#' @export

eval_moo <- function(pop, pareto_ari) {
  # checks
  batch <- sum(pop$params$batch)
  
  stopifnot("There must be more than 1 batch of runs" = batch > 1L,
            "`pop` must be an S3 `pop` object" = inherits(pop, "pop"))
  
  if (is.null(pop$clust)) {
    return(new_stblob(pareto_idx = pareto_idx,
                      clust = NULL,
                      summary = NULL, trace = NULL,
                      filtered_counts = pop$filtered_counts,
                      moo_eval = NULL,
                      obj = obj,
                      data = pop$data,
                      pareto_idx_l = NULL,
                      params = pop$params))
  }
  
  summary <- pop$summary
  trace <- pop$trace
  
  # parse obj
  obj <- c("space_wcd", "-time_wcr", "-time_wce")
  obj_names <- parse_obj(obj)$obj
  obj_space <- select_obj_space(summary = summary, obj = obj, add_cols = "batch")
  
  # obj_space <- summary[ , c(obj, "batch")]
  ## turn max problem into min problem
  # if (length(max_idx) > 0) obj_space[obj[max_idx]] <- obj_space[obj[max_idx]] * -1 
  
  # obtain upper and lower bounds from the all solutions
  ub <- vapply(obj_names, function(i) max(obj_space[[i]]), numeric(1))
  lb <- vapply(obj_names, function(i) min(obj_space[[i]]), numeric(1))
  
  # initialise cumulative indices
  b <- integer()
  # initialise Pareto objective space from the previous cumulative batch
  pareto_s_prev <- NULL
  pareto_idx_l <- list()
  # initialise summary statistics
  igd <- igd_plus <- hv <- cum_n <- numeric()
  summary$pareto <- trace$pareto <- summary$sel <- trace$sel <- FALSE
  
  for (i in 1:batch) {
    # subset solutions till batch i
    b <- append(b, i)
    s <- subset(obj_space, batch %in% b, select = -batch)
    n <- nrow(s)
    cum_n[i] <- n
    
    # skip empty cumulative batch
    if (n == 0) next
    
    # find solutions on the Pareto front
    pareto_idx <- which(moocore::is_nondominated(s))
    pareto_idx_l[[i]] <- pareto_idx
    # normalise objective values of the solutions
    pareto_s <- moocore::normalise(s[pareto_idx, ], to_range = c(0,1), lower = lb, upper = ub)
    
    # compute IGD, IGD+ and Hypervolume
    if (!is.null(pareto_s_prev)) {
      igd[i] <- moocore::igd(x = pareto_s_prev, reference = pareto_s)
      igd_plus[i] <- moocore::igd(x = pareto_s_prev, reference = pareto_s)
    } else {
      igd[i] <- igd_plus[i] <- NA
    }
    # 1.1 such that it would not become 0
    hv[i] <- moocore::hypervolume(x = pareto_s, reference = rep(1.1, length(obj))) ######################################
    pareto_s_prev <- pareto_s
  }
  
  # label summary and trace
  summary$pareto[which(summary$idx %in% pareto_idx)] <-
    trace$pareto[which(trace$idx %in% pareto_idx)] <- 
    summary$sel[which(summary$idx %in% pareto_idx)] <-
    trace$sel[which(trace$idx %in% pareto_idx)] <- TRUE
  
  # FILTER PARETO
  # order idx by objective values
  pareto_obj_space <- subset(cbind(obj_space, summary["idx"], summary["pareto"]), pareto == TRUE)
  
  # pareto_summary <- subset(summary, pareto == TRUE, select = c("idx",obj)) ######################################
  # turn max problem into min problem
  # if (length(max_idx) > 0) pareto_summary[obj[max_idx]] <- pareto_summary[obj[max_idx]] * -1 ######################################
  # rank solutions as find_dup () depends on order
  ranked_idx <- pareto_obj_space[do.call(order, pareto_obj_space[obj_names]), "idx"] ######################################
  
  # find and label distinct solutions in the output
  if (pareto_ari < 1) {
    if (nrow(pareto_summary) > 1) {
      ranked_clust <- pop$clust[ranked_idx, ]
      # find similar on the Pareto front
      sim <- find_dup(ranked_clust, ari = pareto_ari)
      sim_idx <- sim$idx
      if (length(sim_idx) > 0) {
        summary$sel <- trace$sel <- FALSE
        sim_idx <- ranked_idx[sim_idx]
        sel_idx <- ranked_idx[!ranked_idx %in% sim_idx]
        summary$sel[which(summary$idx %in% sel_idx)] <- trace$sel[which(trace$idx %in% sel_idx)] <- TRUE
      }
    }
  } 
  
  # MOO quality check
  moo_eval <- data.frame(igd = igd, igd_plus = igd_plus, hv = hv, cum_n = cum_n)
  
  # reorder summary and trace columns
  summary <- summary[c("idx","sel","pareto", setdiff(names(summary), c("idx","sel","pareto")))]
  trace <- trace[c("idx","sel","pareto", setdiff(names(trace), c("idx","sel","pareto")))]
  
  # update params to include pareto_ari argument
  pop$params$pareto_ari <- pareto_ari
  
  stblob <- new_stblob(pareto_idx = ranked_idx,
                    clust = pop$clust,
                    summary = summary, trace = trace,
                    filtered_counts = pop$filtered_counts,
                    moo_eval = moo_eval,
                    obj = obj, ######################################
                    data = pop$data,
                    pareto_idx_l = pareto_idx_l,
                    params = pop$params)
  
  return(stblob)
}

# filter_pareto ---------------------------------------------------------------
#' Filter solutions on the Pareto front
#' 
#' @description
#' `filter_pareto()` filters redundant solutions on the Pareto front.
#' 
#' @inheritParams stblob
#' @param stblob an S3 `stblob` object.
#' 
#' @inheritSection stblob returns
#' 
#' @export

filter_pareto <- function(stblob, pareto_ari) {
  stopifnot("`ari` must be less than 1 and above 0" = ari > 0 || ari < 1,
            "`stblob` must be an S3 `stblob` object" = inherits(stblob, "stblob"))
  
  summary <- stblob$summary
  trace <- stblob$trace
  
  obj_space <- select_obj_space(summary = summary, obj = stblob$obj, add_cols = c("idx", "pareto"))
  pareto_obj_space <- subset(obj_space, pareto == TRUE)
  
  # pareto_summary <- subset(summary, pareto == TRUE, select = c("idx", obj))
  ## turn max problem into min problem
  # if (length(max_idx) > 0) pareto_summary[obj[max_idx]] <- pareto_summary[obj[max_idx]] * -1 
  
  # rank solutions as find_dup () depends on order
  obj_names <- parse_obj(stblob$obj)$obj
  ranked_idx <- pareto_obj_space[do.call(order, pareto_obj_space[obj_names]), "idx"]
  ranked_clust <- stblob$clust[ranked_idx, ]
  
  # find similar on the Pareto front
  sim <- find_dup(ranked_clust, ari = pareto_ari)
  sim_idx <- sim$idx
  
  if (length(sim_idx) > 0) {
    summary$sel <- trace$sel <- FALSE
    sim_idx <- ranked_idx[sim_idx]
    sel_idx <- ranked_idx[!ranked_idx %in% sim_idx]
    summary$sel[which(summary$idx %in% sel_idx)] <- trace$sel[which(trace$idx %in% sel_idx)] <- TRUE
  }
  
  # update the output
  stblob$summary <- summary
  stblob$trace <- trace
  stblob$pareto_idx <- ranked_idx
  stblob$params$pareto_ari <- pareto_ari
  
  return(stblob)
}

# print.blob ------------------------------------------------------------------
print.stblob <- function(x, ...) {
  cat(paste0("STblob output with ", length(x$pareto_idx), " selected solutions on the Pareto front\n"))
  cat("# indices of selected solutions on the Pareto front:\n")
  print(head(x$pareto_idx, 20))
  if (length(x$pareto_idx) > 20) cat(paste0(" <", length(x$pareto_idx) - 20," more indices>\n"))
  cat(" (ranked by increasing space_wcd, decreasing time_wcr and time_wce)\n")
  cat("\n")
  cat("# clusters:\n")
  print(head(x$clust, c(5, 10)))
  if (ncol(x$clust) > 10) cat(paste0(" <", ncol(x$clust) - 10," more columns (points)>\n"))
  if (nrow(x$clust) > 5) cat(paste0(" <", nrow(x$clust) - 5," more rows (solutions)>\n"))
  cat("\n")
  cat("# summary:\n")
  print(head(x$summary, 5))
  if (nrow(x$summary) > 5) cat(paste0(" <", nrow(x$summary) - 5," more rows>\n"))
  cat("\n")
  cat("# trace:\n")
  print(head(x$trace, 5))
  if (nrow(x$trace) > 5) cat(paste0(" <", nrow(x$trace) - 5," more rows>\n"))
  cat("\n")
  cat("# filtered solution counts:\n")
  print(x$filtered_counts)
  cat("\n")
  cat("# MOO performance:\n")
  print(head(x$moo_eval, 5))
  if (nrow(x$moo_eval) > 5) cat(paste0(" <", nrow(x$moo_eval) - 5," more rows>\n"))
  invisible(x)
}

# summary.blob ----------------------------------------------------------------
summary.pop <- function(x, ...) {
  print(x$summary)
  invisible(x)
}

# helpers ---------------------------------------------------------------------
## select_obj_space -----------------------------------------------------------
select_obj_space <- function(summary, obj, add_cols = NULL) {
  # parse obj
  parsed_obj <- parse_obj(obj)
  obj <- parsed_obj$obj 
  max_idx <- parsed_obj$max_idx
  
  obj_space <- summary[c(obj, add_cols)]
  
  # turn max problem into min problem
  if (length(max_idx) > 0) obj_space[obj[max_idx]] <- obj_space[obj[max_idx]] * -1 
  
  return(obj_space)
}

## parse_obj ------------------------------------------------------------------
parse_obj <- function(obj) {
  max_idx <- grep(pattern = "^-", obj)
  obj <- sub("^-", "", obj)
  out <- list(obj = obj, max_idx = max_idx)
  return(out)
}

## new_stblob -----------------------------------------------------------------
new_stblob <- function(pareto_idx, clust, summary, trace, filtered_counts,
                       moo_eval, obj, data, pareto_idx_l, params) {
  stopifnot(is.null(pareto_idx) || is.numeric(pareto_idx),
            is.null(clust) || is.matrix(clust),
            is.null(summary) || is.data.frame(summary),
            is.null(trace) || is.data.frame(trace),
            is.data.frame(filtered_counts),
            is.null(moo_eval) || is.data.frame(moo_eval),
            is.character(obj),
            is.data.frame(data),
            is.null(pareto_idx_l) || is.list(pareto_idx_l),
            is.null(params) || is.list(params))
  
  structure(
    list(pareto_idx = pareto_idx,
         clust = clust,
         summary = summary,
         trace = trace,
         filtered_counts = filtered_counts,
         moo_eval = moo_eval,
         obj = obj,
         data = data,
         pareto_idx_l = pareto_idx_l,
         params = params),
    class = c("stblob", "pop")
  )
}
